const express = require("express");
const connectDB = require("./config/db");
require("dotenv").config();
const app = express();
app.use(express.json());
app.use(require("cors")());
connectDB();
app.use("/api/auth", require("./routes/authRoutes"));
app.use("/api/blogs", require("./routes/blogRoutes"));
app.listen(5000, () => console.log("Server running on 5000"));